GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmYwMzJlMzIyN2VhMzM4OTQwY2I4N2QiLCJ1c2VybmFtZSI6InNlaGVyIiwiaWF0IjoxNjU5OTA4ODUxLCJleHAiOjE2NTk5OTUyNTF9.2SqmXCV2G-n63bHGs0kYNCrHVl3iawFSmM9P-hQgPt0

{
    "title" : "ask", 
    "author" : "utku",
    "url" : "utku.com", 
    "likes" : 15
}

###
DELETE http://localhost:3001/api/blogs/62eeb6049b8c9fa44e5778b2

###
PATCH http://localhost:3001/api/blogs/62eeb84a685bfbcddd2f3fc0
Content-Type: application/json

{
    "likes" : 28,
    "kamil" : 42
}